### PR TITLE
banner of meetup 13 and changes

### PR DESCRIPTION
**Pull request by geshan**

### CODE REVIEW

**Comment by geshan** [comment]
might conflict :)

**Comment by hardfire** [comment]
does conflict, can you rebase and update the pull request again ?

**Comment by geshan** [comment]
ok

**Comment by hardfire** [comment]
looks like you didn't rebase from the gh-pages branch. so, it still says merge conflicts.

**Comment by geshan** [comment]
closing it in favor of : https://github.com/developers-nepal/php/pull/22

**Pull request closed without merging**
