### PR TITLE
information about php meetup 1, 2 and 3 has been added

### PR DESCRIPTION
**Pull request by samundra**
information about following php meetup has been added:
- php meetup #1
- php  meetup #2
- php meetup #3

### CODE REVIEW

**Comment by hardfire** [comment]
There are some changes to be done especially with the sorting of the meetups . I'll try to update the PR. 

Regards,
Avinash

**Comment by geshan** [comment]
In the mean while can't we merge this @hardfire ?

**Comment by samundra** [comment]
@hardfire lets merge PR for now and work on the changes on separate branch. If you have roadmap for it that would be great :)

**Comment by samundra** [comment]
@hardfire I have streamlined the commit history. All commits are linear.

**Comment by geshan** [comment]
merging it.

**Pull request merged**
